baseURL = "http://muhammedazman.netlify.app/"
languageCode = "en-us"
title = "Muhammed Azman"
paginate = 6

[params]
  # Emoji will show before the blog title on site navbar.
  titleEmoji  = "😎"

  # Logo will show before the blog title on site navbar.
  titleLogo = ""

  # Enable float footnotes.
  # Default to true
  enableFootnotes = true
  siteName = "Muhammed's Protfolio Site"
  siteDesc = "Backend and Front-End works with Java, Spring, Hibernate"
  author = "Muhammed Azman"

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow = 10

  # Show your social information with icon on index bio with `_index.md` content.
  [params.socialOptions]
    dev-to = ""
    email = ""
    facebook = ""
    github = ""
    instagram = ""
    linkedin = ""
    medium = ""
    stack-overflow = ""
    steam = ""
    telegram = ""
    twitter = ""
    twitch = ""
    whatsapp = ""

[menu]
[[menu.header]]
  name = "Articles"
  url = "/articles/"
[[menu.header]]
  name = "Java"
  url = "/java/"

[[menu.footer]]
    name = "RSS"
    url = "/index.xml"

[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
[markup.goldmark.renderer]
  unsafe = true
[markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = false

[param]
  # Minimum word count to display the Table of Contents
  tocMinWordCount = 500
[tableOfContents]
  other = "Table of Contents"

[outputs]
  home = ["HTML", "RSS", "JSON"]