baseURL = "http://muhammedazman.netlify.app/"
languageCode = "en-us"
title = "Muhammed Azman"
paginate = 6

[params]
  # Emoji will show before the blog title on site navbar.
  titleEmoji  = "😎"

  # Logo will show before the blog title on site navbar.
  titleLogo = ""

  # Enable float footnotes.
  # Default to true
  enableFootnotes = true
  siteName = "Muhammed's Protfolio Site"
  siteDesc = "Backend and Front-End works with Java, Spring, Hibernate"
  author = "Muhammed Azman"

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow = 10


  # Show your social information with icon on index bio with `_index.md` content.
  [params.socialOptions]
    dev-to = ""
    email = "vmazman@gmail.com"
    facebook = ""
    github = "https://github.com/muhammedazman"
    instagram = ""
    linkedin = "https://www.linkedin.com/in/muhammed-azman-786960168/"
    codepen = "https://codepen.io/muhammedazman"
    medium = ""
    stack-overflow = ""
    steam = ""
    telegram = ""
    twitter = ""
    twitch = ""
    whatsapp = ""

[menu]
[[menu.header]]
  name = "Articles"
  url = "/articles/"
[[menu.header]]
  name = "Projects"
  url = "/projects/"
[[menu.header]]
  name = "Tutorials"
  url = "/post/tutorials/"

[[menu.footer]]
    name = "RSS"
    url = "/index.xml"

[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]