[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.74.3"
    HUGO_THEME = "repo"

[context.production]
    command = "hugo --gc ../.. -b ${URL}"
    [context.production.environment]
        HUGO_ENV = "production"

[context.branch-deploy]
    command = "hugo --gc ../.. -b ${DEPLOY_PRIME_URL}"

[context.deploy-preview]
    command = "hugo --gc ../.. -b ${DEPLOY_PRIME_URL}"
